server:
  port: 8082

ecommerce:
  database:
    host: @database.host@
    port: @database.port@
    user: @database.user@
    pwd: @database.pwd@
    table: test
  knife4j:
    title: 商品服务
    description: 商品服务
  sentinel:
    dashboard: @sentinel.dashboard@
  nacos:
    dashboard: @nacos.dashboard@