server:
  port: 8083

ecommerce:
  database:
    host: @database.host@
    port: @database.port@
    user: @database.user@
    pwd: @database.pwd@
    table: test
  knife4j:
    title: 购物车服务
    description: 购物车服务
  sentinel:
    dashboard: @sentinel.dashboard@
  nacos:
    dashboard: @nacos.dashboard@
  redis:
    cluster-addr: @redis.cluster-addr@
    expire-hour: 4