server:
  port: 8083

ecommerce:
  database:
    host: 192.168.150.101
    port: 3306
    user: root
    pwd: root
    table: db_cart
  knife4j:
    title: 购物车服务
    description: 购物车服务
  sentinel:
    dashboard: @sentinel.dashboard@
  nacos:
    dashboard: 192.168.150.101:8848
  redis:
    cluster-addr: @redis.cluster-addr@
    expire-hour: 4
  rabbitmq:
    host: @rabbitmq.host@
    port: @rabbitmq.port@
    virtual: /
    user: @rabbitmq.user@
    pwd: @rabbitmq.pwd@