server:
  port: 8080

ecommerce:
  database:
    host: @database.host@
    port: @database.port@
    user: @database.user@
    pwd: @database.pwd@
    table: db_user
  knife4j:
    title: 网关服务
    description: 网关服务
  sentinel:
    dashboard: @sentinel.dashboard@
  nacos:
    dashboard: @nacos.dashboard@

spring:
  cloud:
    gateway:
      routes:
        - id: ai
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**,/api/v1/ais/**
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/carts/**,/api/v1/cart/**
        - id: checkout
          uri: lb://checkout-service
          predicates:
            - Path=/api/v1/checkouts/**,/api/v1/checkout/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**,/api/v1/order/**
        - id: payment
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**,/api/v1/payment/**
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**,/api/v1/product/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**,/api/v1/user/**