server:
  port: 8080

ecommerce:
  database:
    host: @database.host@
    port: @database.port@
    user: @database.user@
    pwd: @database.pwd@
    table: test
  knife4j:
    title: 网关服务
    description: 网关服务
  sentinel:
    dashboard: @sentinel.dashboard@
  nacos:
    dashboard: @nacos.dashboard@

spring:
  cloud:
    gateway:
      routes:
        - id: ai
          uri: lb://ai-service
          predicates:
            - Path=/ai/**,/ais/**
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: checkout
          uri: lb://checkout-service
          predicates:
            - Path=/checkouts/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**,/login,/register