spring:
  profiles:
    active: local
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: ${ecommerce.nacos-addr}
  datasource:
    url: jdbc:mysql://${ecommerce.database.host}:${ecommerce.database.port}/${ecommerce.database.table}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: ${ecommerce.database.user}
    password: ${ecommerce.database.pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001
feign:
  okhttp:
    enabled: true